name: face-attendance-api
services:
  - name: api
    ports:
      - port: 5000
        http:
          path: /api/health
          grace_period: 30s
    regions:
      - fra  # Frankfurt
    instance:
      type: nano  # Free tier
      count: 1
    scaling:
      min: 1
      max: 1
    health_checks:
      http:
        path: /api/health
        port: 5000
        interval: 30
        timeout: 5
        unhealthy_threshold: 3
        healthy_threshold: 2
    env:
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: PORT
        value: "5000"
    docker:
      image: koyeb/face-attendance:latest
    routes:
      - path: /
        port: 5000