# koyeb.yaml - For GitHub deployment with Dockerfile
name: face-attendance-api
services:
  - name: api
    type: web
    ports:
      - port: 5000
        http:
          path: /health
    regions:
      - fra
    instance:
      type: large  # REQUIRED for PyTorch
      count: 1
      disk:
        size_gb: 10
    health_checks:
      http:
        path: /health
        port: 5000
        interval: 30
        timeout: 10
        unhealthy_threshold: 3
        healthy_threshold: 2
        initial_delay: 60
    env:
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: PORT
        value: "5000"
    build:
      # IMPORTANT: Specify Dockerfile build
      dockerfile: ./Dockerfile
    routes:
      - path: /
        port: 5000